### ISSUE TITLE
strange behavior changing to Alt. Display

### ISSUE THREAD

**Issue by Amiga500** [steward-fu/nds_miyoo#16]
on Super Mario Kart, pressing A to accelerate, and then MENU button to change on Alt.Display ( [03] ) the go-kart doesn't accelerate anymore and have to press again A button in order to accelerate

Tested on drastic_82abbf9d61d3c8c628cccd06aa9334a61e50a544. (more accurate on [Drastic-Onion-0.5.zip](https://drive.google.com/file/d/1z36i1l_oNNaX7MzVHQ9eFuyInBGZBIsT/view?usp=sharing) by Totofaki)

**Comment by Sichroteph** [comment]
For example : saving a state while accelerating will stop the motor.
I noticed another thing : pressing select + L will press the button A

**Comment by steward-fu** [comment]
@Sichroteph  it is okay to include the stylus issue in this ticket. I am checking these issues, thanks

**Comment by Sichroteph** [comment]
(Totofaki here)
I hadn't considered something. When sending the key combination to exit using Keymon, it's proven to be more reliable than using Sigterms for now. That's why we employ this method in Onion. However, I didn't anticipate that detecting the menu button and sending "Select + L" would also trigger "Select + Menu," which opens the emulator menu (without exiting) 

I sincerely apologize; I shouldn't have asked you to change "Menu + L" to "Select + L." to exit.

**Comment by steward-fu** [comment]
commit: ad365fc28173771d60ec99f720092e0ff02f7325

Updates:
1. SELECT + L1 (forget to release some keys when exit from DraStic)
2. MENU + A (hotkey is not exchangeable, ex: press A and then press MENU, this is hotkey and won't trigger the hotkey function)
3. MENU + L1 (exit from DraStic emulator)

**Comment by steward-fu** [comment]
@Amiga500  @Sichroteph
If this issue has been fixed in the test build, please help close this issue, thanks

**Comment by Amiga500** [comment]
Ok for me, @Sichroteph it's ok for you too?
